# Site settings
title: Computer Science Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Time waits for no one.
baseurl: # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
repository: jjloyola/jjloyola.github.io


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Javiera Loyola V.
  image    : assets/images/profile.png
  email    : jloyola.vitali@gmail.com
  github   : jjloyola
  twitter  : alldayfreezing
  linkedin : jloyolav
  facebook :


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
#permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
